language: java
jdk:
  - openjdk8
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - oppaakademi4631@gmail.com

before_deploy:
  - zip -r mike-springboot2-webservice *
  - mkdir -p deploy
  - mv mike-springboot2-webservice.zip deploy/mike-springboot2-webservice.zip

deploy:
  - provider: s3
    access_key_id: AKIAZV73HMUF6KEOCDM5
    secret_access_key: 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
    bucket: mike-sprinboot2-build
    region: ap-southeast-1
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deploy: true

  - provider: codedeploy
    access_key_id: AKIAZV73HMUF6KEOCDM5
    secret_access_key: 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

    bucket: mike-springboot2-build
    key: mike-springboot2-webservice.zip

    bundle-type: zip
    application: mike-springboot2-webservice

    deployment-group: mike-springboot2-webservice-group
    region: ap-southeast-1
    wait-until-deploy: true

